### ISSUE TITLE
OTS PutRow 将列Type设置为INT v_int设置成大于0的值不起作用

### ISSUE THREAD

**Issue by dopeter** [aliyun-UED/aliyun-sdk-js#117]
PutRow以及UPDATERow接口
如果某一列的单位是INTEGER
设置VALUE 即 v_int的值为大于0的任意值 
可以操作成功

但再次查询出来值仍为0

**Comment by xiong-liang** [comment]
你好，请在阿里云提交工单，由 OTS 开发人员协助查找原因，找到原因后，我会做相应修改。



------------------------------------------------------------------发件人：dopeter<notifications@github.com>日　期：2017年04月26日 00:43:30收件人：aliyun-UED/aliyun-sdk-js<aliyun-sdk-js@noreply.github.com>抄　送：Subscribed<subscribed@noreply.github.com>主　题：[aliyun-UED/aliyun-sdk-js] OTS PutRow 将列Type设置为INT v_int设置成大于0的值不起作用 (#117)PutRow以及UPDATERow接口

如果某一列的单位是INTEGER

设置VALUE 即 v_int的值为大于0的任意值

可以操作成功
但再次查询出来值仍为0

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aliyun-UED/aliyun-sdk-js","title":"aliyun-UED/aliyun-sdk-js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aliyun-UED/aliyun-sdk-js"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"OTS PutRow 将列Type设置为INT v_int设置成大于0的值不起作用 (#117)"}],"action":{"name":"View Issue","url":"https://github.com/aliyun-UED/aliyun-sdk-js/issues/117"}}}
