### ISSUE TITLE
OSS error: The Content-MD5 you specified was invalid.

### ISSUE THREAD

**Issue by nicolasxu** [aliyun-UED/aliyun-sdk-js#148]
message: 'The Content-MD5 you specified was invalid.',
  code: 'InvalidDigest',
  headers:
   { server: 'AliyunOSS',
     date: 'Tue, 16 Jan 2018 15:26:20 GMT',
     'content-type': 'application/xml',
     'content-length': '318',
     connection: 'close',
     'x-oss-request-id': '5A5E1990952383AD27B700B9',
     'x-oss-server-time': '46' },
  time: 2018-01-16T15:26:20.277Z,
  statusCode: 400,
  retryable: false }

**Comment by xiong-liang** [comment]
Hi，pls provide your OS information.



                                                                                                                                                                                                                                                                                                                                                                                    商陆                                                                                                    阿里巴巴                                                                                                                                            电话：057128223456-81517457                                                                                                        邮箱：xiongliang.xl@alibaba-inc.com                                                                                                        地址：北京-北京-朝阳-阿里中心.望京A座                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                阿里巴巴                                                                                                                                                                                          企业主页                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   注意 : 本电邮(包括任何附件)含有机密资料及可能受法律保护。如您错误收到此电邮，敬请以电邮通知寄件人，于您的系统内删除本信息，及不可将本电邮复印或用作任何用途或对任何人士透露本邮件之内容。多谢合作!
Notice: This email (including any attachments) is confidential and may be legally privileged.
If you received this email in error, please notify us by reply e-mail, delete this message from your system and do not copy it or use it for any purpose or disclose its contents to any other person. Thank you.            ------------------------------------------------------------------发件人：Nicolas Xu<notifications@github.com>日　期：2018年01月16日 23:29:26收件人：aliyun-UED/aliyun-sdk-js<aliyun-sdk-js@noreply.github.com>抄　送：Subscribed<subscribed@noreply.github.com>主　题：[aliyun-UED/aliyun-sdk-js] OSS error: The Content-MD5 you specified was invalid. (#148)message: 'The Content-MD5 you specified was invalid.',

code: 'InvalidDigest',

headers:

{ server: 'AliyunOSS',

date: 'Tue, 16 Jan 2018 15:26:20 GMT',

'content-type': 'application/xml',

'content-length': '318',

connection: 'close',

'x-oss-request-id': '5A5E1990952383AD27B700B9',

'x-oss-server-time': '46' },

time: 2018-01-16T15:26:20.277Z,

statusCode: 400,

retryable: false }

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aliyun-UED/aliyun-sdk-js","title":"aliyun-UED/aliyun-sdk-js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aliyun-UED/aliyun-sdk-js"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"OSS error: The Content-MD5 you specified was invalid. (#148)"}],"action":{"name":"View Issue","url":"https://github.com/aliyun-UED/aliyun-sdk-js/issues/148"}}}
